name: 'ftp-delete-action'
author: 'Stephan Thierry <stephan@protek.dk>'
description: 'Automate deleting files via FTP using this GitHub action.'
inputs:
  host:
    description: 'FTP host'
    required: true
  user:
    description: 'FTP user'
    required: true
  password:
    description: 'FTP password'
    required: true
  remoteFiles:
    description: 'Remote files separated by ; (wildcards accepted)'
    required: true
    default: ''
  remoteDirectories:
    description: 'Remote directories separated by ";" (wildcards accepted)'
    required: false
    default: ''
  workingDir:
    description: 'Working directory'
    required: false
    default: '/'
  ignoreSSL:
    description: 'Ignore invalid TLS/SSL certificate (1=ignoreSSL)'
    required: false
    default: '0'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'orange'
  icon: 'delete'
